
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// NOTE: (radiance, atomic_counter) --> (radiance, opacity)
layout(RGBA8) uniform restrict volatile image3D voxels;

void main() {
  const ivec3 vpos = ivec3(gl_GlobalInvocationID.xyz); 
  const vec4 raw = imageLoad(voxels, vpos);
  vec4 value = raw;
  if (value.a != 0.0f) {
    value.a = 1.0f;
    imageStore(voxels, vpos, value);
  } 
}
